name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    name: Legacy Compatibility
    runs-on: ubuntu-latest

    steps:
      - name: Skip legacy release workflow
        run: echo "This release workflow has been deprecated in favor of release-beta.yml and release-stable.yml."
        shell: bash